---
- name: Filter List Of Dictionaries
  hosts: localhost
  vars:
    names: [{
      "first": "Paul",
      "last": "Thompson",
      "mobile": "+1-234-31245543",
      "ctc": "100000",
      "address":{
        "city": "LasVegas",
        "country": "USA"}
      }, {
       "first": "Rod",
        "last": "Johnson",
        "mobile": "+1-584-31551209",
        "ctc": "300000",
        "address":{
          "city": "Boston",
          "country": "USA"}
      }, {
        "first": "Sarav",
        "last": "AK",
        "mobile": "+919876543210",
        "ctc": "200000",
        "address":{
          "city": "Chennai",
          "country": "India"}
      }
    ]
  tasks:
    # Map Filter only selective attributes from list of objects [{},{}]
    - name: Select and Extract only the cities
      ansible.builtin.debug:
        msg: "{{ names | map(attribute='address') | map(attribute='city') }}"

    # using attirubtes with list of objects [{},{}] - Selecting only mobile numbers
    - name: Select and Extract only mobile numbers
      ansible.builtin.debug:
        msg: "{{ names | map(attribute='mobile') }}"


    - name: Select and Extract
      ansible.builtin.debug:
        msg:
        # Select Attributes FirstName Joined with Comma in Singleline ( By Default it returns a List)
          - "{{ names | map(attribute='first') | join(',') }}"
        # Select Attributes LastName Joined with Comma in Singleline ( By Default it returns a List)
          - "{{ names | map(attribute='last') | join(',') }}"
        # Select Attributes LastName and convert to uppercase
          - "{{ names | map(attribute='last') | map('upper') }}"
        # Convert the CTC attriute to float value
          - "{{ names | map(attribute='ctc') | map('float') }}"
        # Appending USD to each CTC value and print
          - "{{ names | map(attribute='ctc') | product(['USD']) | map('join', ' ') }}"
        # Appending @gmail.com and @kyndryl.com for every record
          - "{{ names | map(attribute='first') | product(['gmail.com', 'kyndryl.com']) | map('join', '@') }}"
