---
- name: "YAML anchors and aliases: sharing variable values"
  hosts: localhost
  gather_facts: false
  vars:
    app1:
      jvm: &jvm_opts
        opts: '-Xms1G -Xmx2G'
        port: 1000
        path: /usr/lib/app1
    app2:
      jvm:
        <<: *jvm_opts
        path: /usr/lib/app2
  tasks:
    - name: "Print app1"
      ansible.builtin.debug:
       var: app1

    - name: "Print app1"
      ansible.builtin.debug:
       var: app2
