---
- name: "This is a Example of Writing String To CSV File"
  hosts: localhost
  gather_facts: false
  vars:
    list1: ['1', '2', '3', '4', '5', '6', '7', '8', '9']
    list2: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
    list3: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
  tasks:
    - name: "Write Lines To File - SIMPLE"
      ansible.builtin.copy:
        content: "{{ [1,2,3] | zip(['a','b','c']) | map('join', ',')  | join('\n') }}"
        dest: "library/vm_details1.csv"
        mode: '0700'

    - name: "Write Lines To File - COMPLEX"  # noqa no-tabs
      ansible.builtin.copy:
        content: "{{ list1 | zip(list2 , list3) | map('join', '\t')  | join('\n') }}"
        dest: "library/vm_details2.csv"
        mode: '0700'

    - name: "Read File"
      ansible.builtin.debug:
        msg: "the value of foo.txt is {{lookup('ansible.builtin.file', '/etc/foo.txt') }}"
